import Link from "next/link";
import { Activity, ArrowRight, CalendarCheck2, ClipboardCheck, Target, UsersRound } from "lucide-react";
import PageIntro from "@/components/dashboard/PageIntro";
import StatCard from "@/components/dashboard/StatCard";
import EmptyState from "@/components/dashboard/EmptyState";
import { currentUser } from "@/lib/server-auth";
import { getCoachDashboard, getCoachEnrollments } from "@/lib/dashboard-data";
import { AttendanceBars } from "@/components/dashboard/DashboardCharts";
import { connectDB } from "@/lib/mongodb";
import Attendance from "@/models/Attendance";
import { dateLabel } from "@/lib/utils";

export const dynamic = "force-dynamic";

export default async function CoachDashboardPage() {
  const user = await currentUser();
  const [summary, enrollments] = await Promise.all([getCoachDashboard(user.id), getCoachEnrollments(user.id)]);
  let recentAttendance = [];
  if (process.env.MONGODB_URI) { await connectDB(); recentAttendance = await Attendance.find({ coach: user.id }).sort({ date: -1 }).limit(6).populate("student", "name").populate("sport", "name").lean(); }
  const activeStudents = enrollments.filter((row) => row.status === "active").length;
  const average = summary.summary.attendanceRate || (enrollments.length ? Math.round(enrollments.reduce((sum, row) => sum + (row.attendanceRate || 0), 0) / enrollments.length) : 0);
  return <div><PageIntro eyebrow={`Welcome back, ${user.name?.split(" ")[0]}`} title="Help every session count." description="Your students, today’s work, and a few next steps for the academy." /><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5"><StatCard icon={UsersRound} label="Total assigned students" value={summary.summary.assigned} note="Assigned to your roster" /><StatCard icon={ClipboardCheck} label="Active students" value={activeStudents} note="Currently training" tone="blue" /><StatCard icon={CalendarCheck2} label="Today’s attendance" value={summary.summary.todaysAttendance || 0} note="Sessions recorded today" tone="orange" /><StatCard icon={Activity} label="Average attendance" value={`${average}%`} note="Across student memberships" tone="green" /><StatCard icon={Target} label="Average progress" value={`${summary.summary.progress}%`} note="Latest coach review by student" /></div>
    <div className="mt-5 grid gap-4 xl:grid-cols-[1fr_1fr]"><section className="surface-card p-5"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.13em] text-slate-400">The routine</p><h3 className="mt-1 text-sm font-bold text-navy">Attendance in recent sessions</h3></div><Link href="/dashboard/coach/attendance" className="text-[10px] font-bold text-blue">Mark attendance</Link></div><div className="mt-4"><AttendanceBars data={summary.attendance} /></div></section><section className="surface-card p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.13em] text-slate-400">On the field</p><h3 className="mt-1 text-sm font-bold text-navy">Recent attendance updates</h3></div><ClipboardCheck size={16} className="text-blue" /></div>{recentAttendance.length ? <div className="mt-4 grid gap-2">{recentAttendance.map((row) => <div key={row._id} className="flex items-center justify-between rounded-xl bg-paper px-3 py-2.5"><div><p className="text-[10px] font-semibold text-navy">{row.student?.name} · {row.sport?.name}</p><p className="mt-1 text-[9px] text-slate-500">{dateLabel(row.date)}</p></div><span className={row.status === "present" ? "status-good" : "status-warn"}>{row.status}</span></div>)}</div> : <div className="mt-4"><EmptyState title="A fresh start." description="Your next attendance update will appear here." action={<Link className="inline-flex items-center gap-1 text-[10px] font-bold text-blue" href="/dashboard/coach/attendance">Open attendance <ArrowRight size={12} /></Link>} /></div>}</section></div>
    <section className="mt-5 surface-card p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.13em] text-slate-400">Your group</p><h3 className="mt-1 text-sm font-bold text-navy">Students to keep moving</h3></div><Link href="/dashboard/coach/students" className="text-[10px] font-bold text-blue">View student list</Link></div>{enrollments.length ? <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{enrollments.slice(0, 3).map((row) => <article key={row._id} className="rounded-xl border border-slate-100 p-4"><div className="flex items-center justify-between"><p className="text-xs font-bold text-navy">{row.student?.name}</p><span className="pill">{row.sport?.name}</span></div><p className="mt-2 text-[10px] text-slate-500">{row.latestProgress?.skillLevel || "Getting started"} · {row.latestProgress?.overallProgress || 0}% progress</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-orange" style={{ width: `${row.latestProgress?.overallProgress || 0}%` }} /></div></article>)}</div> : <div className="mt-4"><EmptyState title="No active students yet." description="New memberships will appear in your workspace once the academy assigns them." /></div>}</section>
  </div>;
}
