"use client";
import { useState } from "react";
import { Bell, CheckCheck } from "lucide-react";
import { dateLabel } from "@/lib/utils";

export default function NotificationBell() {
  const [open, setOpen] = useState(false); const [items, setItems] = useState(null); const [busy, setBusy] = useState(false); const unread = (items || []).filter((item) => !item.readAt).length;
  async function show() { const next = !open; setOpen(next); if (next && items === null) { setBusy(true); try { const response = await fetch("/api/notifications"); const data = await response.json(); if (response.ok) setItems(data.notifications); } finally { setBusy(false); } } }
  async function markAll() { setBusy(true); try { await fetch("/api/notifications", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ markAll: true }) }); setItems((current) => (current || []).map((item) => ({ ...item, readAt: new Date().toISOString() }))); } finally { setBusy(false); } }
  return <div className="relative"><button className="relative grid h-9 w-9 place-items-center rounded-lg border border-slate-200 text-slate-500 hover:bg-slate-50" onClick={show} aria-label={`Notifications${unread ? `, ${unread} unread` : ""}`} aria-expanded={open}><Bell size={16} />{unread > 0 && <span className="absolute right-1.5 top-1.5 h-2 w-2 rounded-full border border-white bg-orange" />}</button>{open && <div className="absolute right-0 top-full z-50 mt-2 w-[min(340px,calc(100vw-32px))] overflow-hidden rounded-xl border border-slate-200 bg-white shadow-xl"><div className="flex items-center justify-between border-b border-slate-100 px-4 py-3"><div><p className="text-[11px] font-bold text-navy">Notifications</p><p className="mt-0.5 text-[9px] text-slate-400">{unread} unread</p></div>{unread > 0 && <button disabled={busy} onClick={markAll} className="inline-flex items-center gap-1 text-[9px] font-semibold text-blue"><CheckCheck size={12} /> Mark all read</button>}</div><div className="max-h-[360px] overflow-auto">{busy && !items ? <p className="p-5 text-center text-[10px] text-slate-400">Loading…</p> : items?.length ? items.map((item) => <article key={item._id} className={`border-b border-slate-50 px-4 py-3 ${item.readAt ? "bg-white" : "bg-blue-soft/60"}`}><div className="flex items-start gap-2"><span className={`mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full ${item.readAt ? "bg-slate-200" : "bg-orange"}`} /><div><p className="text-[10px] font-semibold text-navy">{item.title}</p><p className="mt-1 text-[9px] leading-5 text-slate-500">{item.message}</p><p className="mt-1 text-[8px] text-slate-400">{dateLabel(item.createdAt, { day: "numeric", month: "short", hour: "numeric", minute: "2-digit" })}</p></div></div></article>) : <p className="p-5 text-center text-[10px] text-slate-400">You’re all caught up.</p>}</div><button className="w-full border-t border-slate-100 px-4 py-2.5 text-center text-[9px] font-semibold text-slate-500 hover:bg-slate-50" onClick={() => setOpen(false)}>Close</button></div>}</div>;
}
