"use client";
import { useMemo, useState } from "react";
import { Search, ShieldCheck, ShieldOff, Trash2 } from "lucide-react";
import PageIntro from "@/components/dashboard/PageIntro";
import { dateLabel } from "@/lib/utils";

export default function AdminUserDirectory({ initialUsers }) {
  const [users, setUsers] = useState(initialUsers || []); const [search, setSearch] = useState(""); const [role, setRole] = useState("all"); const [busy, setBusy] = useState(""); const [message, setMessage] = useState("");
  const filtered = useMemo(() => users.filter((user) => `${user.name} ${user.email}`.toLowerCase().includes(search.toLowerCase()) && (role === "all" || user.role === role)), [users, search, role]);
  async function toggle(user) { setBusy(user._id); setMessage(""); try { const response = await fetch("/api/admin/users", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: user._id, isActive: !user.isActive }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Could not update this account."); setUsers((current) => current.map((row) => row._id === user._id ? { ...row, isActive: data.user.isActive } : row)); setMessage(`${user.name}’s account is now ${data.user.isActive ? "active" : "disabled"}.`); } catch (error) { setMessage(error.message); } finally { setBusy(""); } }
  async function removeUser(user) { if (!confirm(`Are you sure you want to remove ${user.name}'s account?`)) return; setBusy(user._id); setMessage(""); try { const response = await fetch(`/api/admin/users?id=${user._id}`, { method: "DELETE" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Could not delete this account."); setUsers((current) => current.filter((row) => row._id !== user._id)); setMessage(`${user.name}’s account has been removed.`); } catch (error) { setMessage(error.message); } finally { setBusy(""); } }
  return <div><PageIntro eyebrow="Access control" title="User accounts" description="Review academy accounts and disable access when needed. Roles are assigned by an administrator." /><div className="surface-card overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row sm:items-center"><p className="mr-auto text-[11px] font-bold text-navy">{users.length} accounts</p><label className="relative block w-full sm:max-w-[240px]"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input className="form-control !py-2 !pl-9 !text-[11px]" placeholder="Search name or email" value={search} onChange={(event) => setSearch(event.target.value)} /></label><select className="form-control !w-full !py-2 !text-[11px] sm:!w-[140px]" value={role} onChange={(event) => setRole(event.target.value)}><option value="all">All roles</option>{["student", "coach", "admin"].map((item) => <option key={item}>{item}</option>)}</select></div>{message && <p role="status" className="mx-4 mt-3 rounded-lg bg-blue-soft px-3 py-2 text-[10px] text-blue">{message}</p>}{filtered.length ? <div className="table-wrap border-0 rounded-none"><table className="data-table"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Phone</th><th>Joined</th><th>Account status</th><th>Action</th></tr></thead><tbody>{filtered.map((user) => <tr key={user._id}><td className="font-semibold text-navy">{user.name}</td><td>{user.email}</td><td><span className="pill capitalize">{user.role}</span></td><td>{user.phone || "—"}</td><td>{dateLabel(user.createdAt)}</td><td><span className={user.isActive ? "status-good" : "status-muted"}>{user.isActive ? "Active" : "Disabled"}</span></td><td><div className="flex items-center gap-1.5"><button disabled={busy === user._id} onClick={() => toggle(user)} className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-2.5 py-1.5 text-[10px] font-semibold text-slate-600 hover:border-blue hover:text-blue disabled:opacity-50">{user.isActive ? <ShieldOff size={13} /> : <ShieldCheck size={13} />}{user.isActive ? "Disable" : "Enable"}</button><button disabled={busy === user._id} onClick={() => removeUser(user)} title="Delete account" className="inline-flex items-center justify-center rounded-lg border border-slate-200 p-1.5 text-[10px] font-semibold text-slate-400 hover:border-red-300 hover:bg-red-50 hover:text-red-600 disabled:opacity-50"><Trash2 size={13} /></button></div></td></tr>)}</tbody></table></div> : <p className="py-10 text-center text-xs text-slate-400">No accounts match those filters.</p>}</div></div>;
}
