"use client";
import { useMemo, useState } from "react";
import { Search } from "lucide-react";
import { dateLabel } from "@/lib/utils";
import EmptyState from "@/components/dashboard/EmptyState";

export default function CoachStudentsTable({ initialEnrollments }) {
  const [search, setSearch] = useState(""); const [level, setLevel] = useState("all"); const [attendance, setAttendance] = useState("all");
  const rows = useMemo(() => initialEnrollments.filter((item) => `${item.student?.name} ${item.student?.email}`.toLowerCase().includes(search.toLowerCase()) && (level === "all" || item.latestProgress?.skillLevel === level) && (attendance === "all" || (attendance === "regular" ? item.attendanceRate >= 80 : item.attendanceRate < 80))), [initialEnrollments, search, level, attendance]);
  return <div className="surface-card overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row sm:items-center"><p className="mr-auto text-[11px] font-bold text-navy">{rows.length} active students</p><label className="relative block w-full sm:max-w-[240px]"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input className="form-control !py-2 !pl-9 !text-[11px]" placeholder="Search by name" value={search} onChange={(event) => setSearch(event.target.value)} /></label><select className="form-control !w-full !py-2 !text-[11px] sm:!w-[160px]" value={level} onChange={(event) => setLevel(event.target.value)}><option value="all">All skill levels</option>{["Beginner", "Intermediate", "Advanced", "Professional"].map((item) => <option key={item}>{item}</option>)}</select><select className="form-control !w-full !py-2 !text-[11px] sm:!w-[160px]" value={attendance} onChange={(event) => setAttendance(event.target.value)}><option value="all">All attendance</option><option value="regular">80% and above</option><option value="needs-follow-up">Below 80%</option></select></div>{rows.length ? <div className="table-wrap border-0 rounded-none"><table className="data-table"><thead><tr><th>Student</th><th>Sport</th><th>Membership</th><th>Attendance</th><th>Skill level</th><th>Progress</th><th>Membership status</th><th>Expires</th></tr></thead><tbody>{rows.map((row) => <tr key={row._id}><td><span className="font-semibold text-navy">{row.student?.name}</span><span className="mt-1 block text-[10px] text-slate-400">{row.student?.email}</span></td><td>{row.sport?.name}</td><td>{row.membershipPlan?.name}</td><td>{row.attendanceRate}%</td><td>{row.latestProgress?.skillLevel || "Getting started"}</td><td><span className="font-semibold text-blue">{row.latestProgress?.overallProgress || 0}%</span></td><td><span className={row.status === "active" ? "status-good" : "status-warn"}>{row.status || "active"}</span></td><td>{dateLabel(row.endDate)}</td></tr>)}</tbody></table></div> : <div className="p-4"><EmptyState title="No students match that filter." description="Try a different search, skill level, or attendance range." /></div>}</div>;
}
